# 控制台日志高亮
spring:
  output:
    ansi:
      enabled: always
  datasource:
    db:
      db01:
        url: jdbc:mysql://localhost:3306/db_01?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: root
        password: root
      db02:
        url: jdbc:mysql://localhost:3306/db_02?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: root
        password: root
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true

logging:
  level:
    com:
      example: info