env: ${spring.profiles.active}
#appId 同来区别不同的配置
app.id: SampleApp
#apollo服务器地址
apollo.meta: http://my-host.com:8080
spring:
  application:
    name: springboot-simple-app-${env}
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://my-host.com:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jackson:
    default-property-inclusion: non_null
  # redis 配置
  redis:
    host: my-host.com
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  notEmpty: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ['health','info']
info:
  app:
    name: ${spring.application.name}
    version: 1.0
